virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "cd proto; make"
  - "cd artifacts; make"
script: cd ..; PYTHONPATH=. python grr/run_tests.py
